### ISSUE TITLE
US Check Writing

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-usa#10]
# Improvements

* Remove the dependency on l10n_us_check_writing
* Add the dependency on account_check_printing_report_base in https://github.com/OCA/account-payment
* Relicense the module to AGPL-3

**Comment by smangukiya** [comment]
@max3903 : As you mention,

Add the dependency on account_check_printing_report_base in https://github.com/OCA/account-payment

I found account_check_printing_report_base module in version 9.0 rather in v10.0. So, I will be required to migrate it to v10 first right?

Thanks!

**Comment by max3903** [comment]
@smangukiya Yes! I just assigned it to you here:
https://github.com/OCA/account-payment/issues/102

Thanks!
