### ISSUE TITLE
Is branch 9 working?

### ISSUE THREAD

**Issue by elfeffe** [OCA/l10n-usa#14]
I saw you are working on v10, but is 9 available for production?

**Comment by pedrobaeza** [comment]
No, it isn't, Federico. There's no work made for that version.

**Comment by max3903** [comment]
@elfeffe Which module/feature do you want on version 9?

**Comment by elfeffe** [comment]
@max3903 
I want to try the USA localisation on Odoo 9 or 10, I need the whole localisation. Can it be used in production?
Or even 8, is this localisation fully working on any version?

**Comment by max3903** [comment]
@elfeffe 
We have all the modules listed here #5 working on version 9 and being used in production by our customers. Publishing them would require some work/time to match the OCA standards.

Let me see what I can do. Meanwhile, can you review the version 10 modules?

**Comment by elfeffe** [comment]
@max3903 With review you mean install it on 10 and report problems?
I can do that, sure.
And, you mean you have working on 9 the modules listed on your link, and also checked. Not the unchecked ones. No?

**Comment by max3903** [comment]
@elfeffe No need to install them. You can use the runbot link at the bottom of each pull request. Thank you!

On version 9, we have:
-  account_payment_batch_process
-  account_payment_credit_card
-  partner_aging
-  partner_daytopay
-  l10n_us_check_writing_address
-  l10n_us_form_1099
-  account_banking_reconciliation

**Comment by pedrobaeza** [comment]
@max3903 Some of that modules are not "localization" modules, but commodity modules that can be used outside l10n-usa.

**Comment by elfeffe** [comment]
@max3903 Is there any module to import bank statements automatically? Without download files, I have seens that other systems like Xero imports it "automagically".

**Comment by max3903** [comment]
@elfeffe There is one in Odoo Enterprise. Not sure in the OCA. @pedrobaeza Any idea?

**Comment by pedrobaeza** [comment]
No, there isn't any in OCA. Soon, there will be a new agreement in EU for an standard bank statement format, but that doesn't cover US.
