### ISSUE TITLE
[IMP] l10n_us_form_1099: Replace the checkbox by a selection list

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-usa#36]
- [x] Add a new object "1099.type" with a char field "Name"
- [x] Add a many2one field "1099 Type" on res.partner to 1099.type
- [x] Create a SQL view from account.payment with:
* Vendor
* 1099 Type
* Payment
* Date
* Amount
- [x] Add a pivot view with:
* Vendor
* 1099 Type
* Payment
* Date
* Amount
- [x] Add a menu item "1099 Report" under Accounting / Reporting
- [x] Add data for 1099.type with: 1099-A, 1099-B, 1099-C, 1099-CAP, 1099-DIV, 1099-G, 1099-H, 1099-INT, 1099-K, 1099-LTC, 1099-MISC, 1099-OID, 1099-PATR, 1099-Q, 1099-R, 1099-S, 1099-SA, RRB-1099 and SSA-1099

**Comment by max3903** [comment]
Ping @SerenaCyr

**Comment by max3903** [comment]
Ping @murtuzasaleh

**Comment by wolfhall** [comment]
I think it is good to leave the original checkbox in place and add the type selection.  Also, the types should not be hardcoded but a selection that can be edited via configuration settings.

**Comment by max3903** [comment]
@brian10048 I updated the issue description to match what was discussed.

**Comment by brian10048** [comment]
Sounds good.  I can update to make the new object for 1099.type and its associated data.

I've got the model for the SQL view started, but will need help getting the actual query correct.

**Comment by bodedra** [comment]
@brian10048 I have completed with following points and ready for commit. So would you please share your repository access rights with me.

> - Add a new object 'type.1099' with a char field 'Name',
> - Add a many2one field '1099 Type' on res.partner to type.1099,
> - Add data for type.1099 with: 1099-A, 1099-B, 1099-C, 1099-CAP, 1099-DIV, 1099-G, 1099-H, 1099-INT, 1099-K, 1099-LTC, 1099-MISC, 1099-OID, 1099-PATR, 1099-Q, 1099-R, 1099-S, 1099-SA, RRB-1099 and SSA-1099
> - Add security for type.1099 object

Access denied:

![Screenshot from 2019-07-17 13-37-04](https://user-images.githubusercontent.com/14229503/61358541-23c32e00-a898-11e9-901a-8cd691b2d681.png)

CC @max3903 @wolfhall

**Comment by max3903** [comment]
@bodedra Push to `ursais/l10n-usa` and create a pull request against `brian10048/12.0`

**Comment by bodedra** [comment]
@max3903 These is done. So we can close these. Thank you.
