### ISSUE TITLE
ACH credit (payment to vendor) missing generate option

### ISSUE THREAD

**Issue by ashleybarto** [OCA/l10n-usa#83]
How do I generate the ACH file from the payment to the vendor? Check is the only option.

**Comment by bodedra** [comment]
@ashleybarto You need to install the "account_banking_ach_credit_transfer" module to active ACH-OUT payment orders.

**Comment by ashleybarto** [comment]
All of the modules are installed. ach credit transfer, payment partner, payment mode, banking mandate, banking ach base.  I had these installed before and no generate option. Where should it be?

**Comment by bodedra** [comment]
It is generated from the "Payment Orders" action. Go to Vendors > Bills. Find your bill and select it. From the top "Action" button, you will see "Payment Orders".

If it validates the ACH vendor bill, it will generate payment orders.

**Comment by bodedra** [comment]
@ashleybarto If it is resolved, we can close this issue.

**Comment by ashleybarto** [comment]
I think so.  You were very help in pointing out where we can generate the ACH’s


Mr. Ashley Barto
Sr. IT Manager
Regional Demand Manager - Americas

SCHOTT North America, Inc.
Corporate Office
2 International Drive
Rye Brook, NY 10573

Phone/Fax:
Direct: 914.831.2292
General: 914.831.2200
Fax: 914.831.2201


This message contains confidential and privileged information and is intended only for the individuals to whom it is addressed.   It should not be reviewed, retransmitted, disseminated or otherwise used by persons or entities other than the intended recipient.  If you received this message in error, please contact the sender and delete the material from your computer system(s).  Thank you.

**Comment by bodedra** [comment]
That's awesome. Thanks for your confirmation.

Ready to close.
