### ISSUE TITLE
US Tax Calculation & Reporting

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-usa#9]
# Version 13

- [ ] Avalara (http://www.avalara.com)
- [ ] SmartCalcs (https://www.taxjar.com/smartcalcs/):
- [x] Tax Cloud (http://www.taxcloud.com): https://www.odoo.com/apps/modules/13.0/account_taxcloud/
- [ ] Zip-Tax (http://zip-tax.com):

# Version 12

- [x] Avalara (http://www.avalara.com) - https://github.com/sodexis/avatax_connector
- [ ] SmartCalcs: https://www.taxjar.com/smartcalcs/ - By @hveficent - #47 
- [x] Tax Cloud (http://www.taxcloud.com): https://www.odoo.com/apps/modules/12.0/account_taxcloud/
- [ ] Zip-Tax: http://zip-tax.com/

# Version 11

- [ ] Avalara (http://www.avalara.com)
- [ ] SmartCalcs: https://www.taxjar.com/smartcalcs/
- [x] Tax Cloud (http://www.taxcloud.com): https://www.odoo.com/apps/modules/11.0/account_taxcloud/
- [ ] Zip-Tax: http://zip-tax.com/

# Version 10

- [ ] Avalara (http://www.avalara.com) - By @obulkin - https://github.com/OCA/sale-workflow/issues/435
- [ ] SmartCalcs: https://www.taxjar.com/smartcalcs/
- [x] Tax Cloud (http://www.taxcloud.com): https://www.odoo.com/apps/modules/10.0/account_taxcloud/
- [ ] Zip-Tax: http://zip-tax.com/

# Version 9

- [x] Avalara (http://www.avalara.com):
* https://www.odoo.com/apps/modules/9.0/avatax_connector/
* https://www.avalara.com/integrations/odoo9/

# Version 8

- [x] Avalara (http://www.avalara.com): https://www.avalara.com/integrations/odoo8/

**Comment by lasley** [comment]
@max3903 - @obulkin is halfway through migrating avatax to v10

re https://github.com/OCA/sale-workflow/issues/435

**Comment by max3903** [comment]
@lasley Wow! Where does that happen? Any PR we can help with?

**Comment by lasley** [comment]
No PR yet. I don't see a branch associated with our internal ticket either. @obulkin please push your branch and advise (LABS-410).

**Comment by obulkin** [comment]
The code is up: https://github.com/LasLabs/l10n-usa/tree/release/10.0/avatax_connector. I've made a lot of style and organizational changes to bring it more in line with OCA and PEP guidelines and am now identifying/fixing various bugs. It's definitely a work in progress and may not install properly right this minute because I'm in the middle of refactoring one of the models.

**Comment by lasley** [comment]
Thanks for the update @obulkin
